# network.py

In [1]:
import random 
import numpy as np

In [11]:
class Network(object):
    
    def __init__(self, sizes):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y,1) for y in sizes[1:]]
        self.weights = [np.random.randn(x,y)
                       for x,y in zip(sizes[:-1], sizes[1:])]

In [6]:
sizes = [2, 3, 1]
[np.random.randn(y,1) for y in sizes[1:]]


[array([[ 1.97480868],
        [-0.09152534],
        [ 0.47748847]]),
 array([[0.17142948]])]

In [8]:
[np.random.randn(x,y) for x,y in zip(sizes[:-1], sizes[1:])]

[array([[-0.58515016,  0.20675274,  1.05424141],
        [-0.18046364, -1.13680682, -0.44901746]]),
 array([[1.98218411],
        [0.63069134],
        [0.43117637]])]

In [10]:
list(zip(sizes[:-1], sizes[1:]))

[(2, 3), (3, 1)]

In [12]:
net = Network([2, 3, 1])

In [14]:
net.weights[1]

array([[ 0.39421366],
       [-1.19176104],
       [-0.75494892]])